---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: flagger
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: flagger-source
  interval: 1m0s
  targetNamespace: ingress-nginx
  values:
    prometheus:
      install: true
    meshProvider: nginx

