---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-source
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: ingress-nginx
  values:
    controller:
      metrics:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: true
        port: 10254
        
  

